

import type { Metadata } from "next";
import { Head } from 'next/document';

import "./globals.css";
import App from "./page";
import Menu from '@/app/components/menu'

import React from 'react';
import ScrollToTopButton from './components/ScrollToTopButton';
import Headmeta from './components/head';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">


        <Headmeta>

          <body>{children}
            <Menu />
            <ScrollToTopButton />
          </body>
          </Headmeta >
      </html>
    </>
          
                );
}
