
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import App from "./page";
import Menu from '@/app/components/menu'
import Footer from '@/app/components/footer'
import React from 'react';
import ScrollToTopButton from './components/ScrollToTopButton';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>    
    <html lang="en">
     
      <body className={inter.className}>{children}
      <Menu />
      {/* <Footer/> */}
      <ScrollToTopButton />
      </body>
      {/* <Script src='/script/intromove.js' id='tys-home-js' strategy="afterInteractive" />
      <Script src='/script/intro.js' id='tys-js' strategy="afterInteractive" /> */}

    </html>
    </>

  );
}
